db:
  image: postgres
  mem_limit: 128m

uwsgi:
  restart: always
  image: neuropower/neuropower
  command: /code/run_uwsgi.sh
  volumes:
    - .:/code
    - /var/www/static
  links:
    - db
    - redis
  mem_limit: 128m

nginx:
  restart: always
  image: nginx
  mem_limit: 60m
  ports:
    - "80:80"
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
  volumes_from:
    - uwsgi
  links:
    - uwsgi
  mem_limit: 128m

redis:
  restart: always
  image: redis
  command: redis-server --appendonly yes
  mem_limit: 128m


worker:
  image: neuropower/neuropower
  command: /code/run_worker.sh
  volumes_from:
    - uwsgi
  links:
    - db
    - redis
  mem_limit: 128m
